#!/bin/bash

set -eux -o pipefail

# Create and configure s3 bucket
readonly BUCKET="www.charleshooper.net"
aws s3 mb s3://${BUCKET} \
	--region us-west-2 || true
aws s3 website s3://${BUCKET} \
	--region us-west-2 \
	--index-document index.html

# Generate html
LANG=en_US.UTF-8 bundle exec rake generate

# Deploy to s3
aws s3 cp --recursive public/ s3://${BUCKET}/ \
	--region us-west-2 \
	--acl public-read
#--grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

# purge cdn
# TODO(charles) figure out what to do about s3 eventual consistency :(
# curl -X POST -H "Fastly-Key: $FASTLY_KEY" https://api.fastly.com/service/$FASTLY_SERVICE/purge_all
