#!/bin/bash

# Generate
docker-compose run web bundle exec rake generate

# Deploy to VPSes
#SSH_TARGET="cchdotnet@theobroma.plumata.net" bundle exec rake deploy
#SSH_TARGET="cchdotnet@lagunitas.plumata.net" bundle exec rake deploy

# Deploy to Heroku
git add .
git commit -a -m 'auto-commit on deploy'
git push origin master
git push heroku master

